### ISSUE TITLE
External Library Support

### ISSUE THREAD

**Issue by remo5000** [source-academy/cadet-frontend#203]
### TODO
- [x] Store `externals` in state (#198)
- [x] Load all libraries using a single script
- [x] Make libraries work
  - [x] Sound
  - [x] Graphics
  - [ ] Deathcube
  - [ ] Metacircular Interpreter
- ~~[ ] Externals are defined together with library~~
- [ ] Minify public libraries on build (?)

**Comment by ningyuansg** [comment]
Closed, or some tasks complete?

**Comment by remo5000** [comment]
@ningyuansg updated. Do you think storing the externals near the library (in the public folder) is a good idea? I'd rather expose as little information as possible

**Comment by ningyuansg** [comment]
I don't see a good way to hide this information, given that all our stuff runs on client side, and that this repo is public.
